### ISSUE TITLE
interest in this port?

### ISSUE THREAD

**Issue by jeremysimmons** [codeborne/nselenide#1]
C# 6.0 will have support for static using. VB.Net already does. The java selenide api is highly dependent on this language feature as the entry point to Selenide. 
http://roslyn.codeplex.com/wikipage?title=Language%20Feature%20Status&referringTitle=Documentation

Is there interest from codeborne in maintaining a port if an initial fork is done?

**Comment by asolntsev** [comment]
Hi @jeremysimmons!
No, Codeborne does not have plans to develop NSelenide. This repository was created by initiative of @Fulcrum81, but it doesn't seem to go well... 

So, what is your plan? 
Do you want to create own fork, or we could add you to the [NSelenide team](https://github.com/orgs/codeborne/teams/nselenide-team)?

**Comment by jeremysimmons** [comment]
My plan is to port the code to C# 6.0 w/ VS2015 CTP6, and iterate as CTPs come out.
I'd prefer to have an idiomatic port that uses C#/.Net concepts over java.

As for forking to my own github account vs NSelenide team, I'll defer to you. I don't have a strong opinion at this point.

Right now I will fork the existing codeborne/nselenide and send a pull request when I have something to show for myself. If you feel my port has merit and can pass any acceptance or regression suites for your library, and you feel it's worth attaching the codeborne name to, then I would certainly accept being made a member of the codeborne github organization with permission for codeborne/nselnide repository. I'd prefer to earn that though.

Codeborne has done a great job with NSelenide, and I'm excited to learn more of the API and improvements made on top of Selenium. If any of the library maintainers are available to answer questions about the api as they come up, that would be appreciated.

I think this would be a great project to showcase the capabilities of "static using" in C# 6 that test library developers can take advantage of. Ultimately, I'd like to pitch a finished library to one of the microsoft community evangelists Scott Hanselman (hanselman.com) to earn a place on his weekly podcast. I'd like to work towards getting a nomination for MVP this year.
